In [4]:
# !pip3 install  python-dotenv
# !pip install importlib
# !pip3 install langchain_openai
!pip3 install langchain_experimental

Collecting langchain_experimental
  Downloading langchain_experimental-0.3.4-py3-none-any.whl.metadata (1.7 kB)
Collecting langchain-community<0.4.0,>=0.3.0 (from langchain_experimental)
  Downloading langchain_community-0.3.31-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<0.4.0,>=0.3.28 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain_experimental) (0.3.79)
Collecting langchain<2.0.0,>=0.3.27 (from langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading langchain-0.3.27-py3-none-any.whl.metadata (7.8 kB)
Collecting SQLAlchemy<3.0.0,>=1.4.0 (from langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (6.0.3)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading aiohttp-3.13.0-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (9.1.2)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Using cached pydantic_settings-2.11.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.4.34)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=2.1.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.2.6)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading frozenlist-1.8.0-cp313-cp313-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading multidict-6.7.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading propcache-0.4.1-cp313-cp313-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading yarl-1.22.0-cp313-cp313-win_amd64.whl.metadata (77 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<1.0.0,>=0.3.9 (from langchain<2.0.0,>=0.3.27->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading langchain_text_splitters-0.3.11-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain<2.0.0,>=0.3.27->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-core<0.4.0,>=0.3.28->langchain_experimental) (1.33)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langchain-core<0.4.0,>=0.3.28->langchain_experimental) (4.15.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\hahtsham\appdata\roaming\python\python313\site-packages (from langchain-core<0.4.0,>=0.3.28->langchain_experimental) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<0.4.0,>=0.3.28->langchain_experimental) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.25.0)
Requirement already satisfied: anyio in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (4.11.0)
Requirement already satisfied: certifi in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2025.10.5)
Requirement already satisfied: httpcore==1.* in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.0.9)
Requirement already satisfied: idna in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.1 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.41.1)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (2.5.0)
Collecting greenlet>=1 (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<0.4.0,>=0.3.0->langchain_experimental)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in c:\users\hahtsham\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<0.4.0,>=0.3.0->langchain_experimental) (1.3.1)
Downloading langchain_experimental-0.3.4-py3-none-any.whl (209 kB)
Downloading langchain_community-0.3.31-py3-none-any.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ------------ --------------------------- 0.8/2.5 MB 5.3 MB/s eta 0:00:01
   --------------------------------- ------ 2.1/2.5 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 5.2 MB/s  0:00:00
Downloading aiohttp-3.13.0-cp313-cp313-win_amd64.whl (450 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain-0.3.27-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 7.1 MB/s  0:00:00
Downloading langchain_text_splitters-0.3.11-py3-none-any.whl (33 kB)
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
Downloading multidict-6.7.0-cp313-cp313-win_amd64.whl (45 kB)
Using cached pydantic_settings-2.11.0-py3-none-any.whl (48 kB)
Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----------------------------- ---------- 1.6/2.1 MB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 6.6 MB/s  0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading yarl-1.22.0-cp313-cp313-win_amd64.whl (86 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading frozenlist-1.8.0-cp313-cp313-win_amd64.whl (43 kB)
Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading propcache-0.4.1-cp313-cp313-win_amd64.whl (40 kB)
Installing collected packages: propcache, mypy-extensions, multidict, marshmallow, httpx-sse, greenlet, frozenlist, attrs, aiohappyeyeballs, yarl, typing-inspect, SQLAlchemy, aiosignal, pydantic-settings, dataclasses-json, aiohttp, langchain-text-splitters, langchain, langchain-community, langchain_experimental

   ------ ---------------------------------  3/20 [marshmallow]
   ---------- -----------------------------  5/20 [greenlet]
   ---------- -----------------------------  5/20 [greenlet]
   ------------ ---------------------------  6/20 [frozenlist]
   -------------- -------------------------  7/20 [attrs]
   -------------- -------------------------  7/20 [attrs]
   ---------------- -----------------------  8/20 [aiohappyeyeballs]
   ------------------ ---------------------  9/20 [yarl]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   ---------------------- ----------------- 11/20 [SQLAlchemy]
   -------------------------- ------------- 13/20 [pydantic-settings]
   ---------------------------- ----------- 14/20 [dataclasses-json]
   ------------------------------ --------- 15/20 [aiohttp]
   ------------------------------ --------- 15/20 [aiohttp]
   ------------------------------ --------- 15/20 [aiohttp]
   ------------------------------ --------- 15/20 [aiohttp]
   -------------------------------- ------- 16/20 [langchain-text-splitters]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]
   ---------------------------------- ----- 17/20 [langchain]

In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

False

In [37]:
%run Mcamelot_p

C:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:8: SyntaxWarning: invalid escape sequence '\s'
  lattice_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='lattice', suppress_stdout=False)
C:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:9: SyntaxWarning: invalid escape sequence '\s'
  stream_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='stream', suppress_stdout=False)
C:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:15: SyntaxWarning: invalid escape sequence '\s'
  lattice_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='lattice', suppress_stdout=False)
C:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:16: SyntaxWarning: invalid escape sequence '\s'
  stream_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='stream', suppress_stdout=False)

In [39]:
#from Mcamelot_p.py import extract_table
import Mcamelot_p
#importlib.reload(Mcamelot_p)
from Mcamelot_p import extract_table

c:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:8: SyntaxWarning: invalid escape sequence '\s'
  lattice_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='lattice', suppress_stdout=False)
c:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:9: SyntaxWarning: invalid escape sequence '\s'
  stream_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='stream', suppress_stdout=False)
c:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:15: SyntaxWarning: invalid escape sequence '\s'
  lattice_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='lattice', suppress_stdout=False)
c:\Users\hahtsham\work\ICR\Multiple_OCR\Mcamelot_p.py:16: SyntaxWarning: invalid escape sequence '\s'
  stream_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='stream', suppress_stdout=False)

In [13]:
api_key = os.getenv("OPEN_API_KEY")
load_dotenv()
os.environ['OPENAI_API_KEY'] = os.getenv("OPEN_API_KEY")

In [14]:
from dotenv import dotenv_values

In [40]:
table = Mcamelot_p.extract_table('d')

In [ ]:
import pandas as pd
from langchain_openai import ChatOpenAI
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent

# 1. Your Camelot DataFrame



df = stream_tables[0].df
df1 = table[0].df


# 2. Initialize the LLM
llm = ChatOpenAI(temperature=0, model="gpt-4o-mini")

<>:9: SyntaxWarning: invalid escape sequence '\s'
<>:10: SyntaxWarning: invalid escape sequence '\s'
<>:9: SyntaxWarning: invalid escape sequence '\s'
<>:10: SyntaxWarning: invalid escape sequence '\s'
C:\Users\hahtsham\AppData\Local\Temp\ipykernel_39056\1505203550.py:9: SyntaxWarning: invalid escape sequence '\s'
  lattice_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='lattice', suppress_stdout=False)
C:\Users\hahtsham\AppData\Local\Temp\ipykernel_39056\1505203550.py:10: SyntaxWarning: invalid escape sequence '\s'
  stream_tables = camelot.read_pdf('c:\\Users\\hahtsham\\work\\ICR\\Multiple_OCR\sample_with_tables.pdf', pages='all', flavor='stream', suppress_stdout=False)

In [31]:
df

,0,1,2,3
0,Table 1: Employee Performance,,,
1,Employee,Department,Performance Score,Experience (Years)
2,Alice,Sales,89,5
3,Bob,Marketing,92,4
4,Charlie,HR,85,6
5,Diana,Engineering,95,3

In [33]:
df1

          0            1                  2                   3
0  Employee   Department  Performance Score  Experience (Years)
1     Alice        Sales                 89                   5
2       Bob    Marketing                 92                   4
3   Charlie           HR                 85                   6
4     Diana  Engineering                 95                   3

In [42]:

agent = create_pandas_dataframe_agent(
            llm,
            df1,
            verbose=False,
            agent_type="openai-functions",
            allow_dangerous_code=True
        )

# 4. Ask a question
# question = "What is the average experience years for the employees?"
# response = agent.invoke({"input": question})

# print(response['output'])
while True:
    query = input("Please type your query: ")
    if query.lower() in ['q', 'quit', 'close']:
        break
    response = agent.invoke({"input": query})
    print(response['output'])

In [ ]:
#